save_dir: example/ddg_synthetic/FoldX/example_train/outputs/
name: Graphinity-example_train
train: True
test: True

logger_params:
  wandb_bool: False
  ## uncomment and update for logging with Weights and Biases (wandb)
  #entity: # wandb username
  #wandb: # wandb project name
  #group: # wandb group name
  #log_interval: 10
  #print_interval: 50

model: ddgEGNN
model_params:
  num_node_features: 12
  lr: 1.e-3 
  weight_decay: 1.e-16
  balanced_loss: False
  dropout: 0.2
  num_edge_features: 1
  egnn_layer_hidden_nfs: [128, 128, 128]
  embedding_in_nf: 128
  embedding_out_nf: 128
  num_classes: 1
  attention: False
  residual: True
  normalize: False
  tanh: True
  update_coords: True
  scheduler: CosineAnnealing
  norm_nodes: None
  #max_pool_graphvectors: False #True

trainer_params:
  accumulate_grad_batches: 1
  max_epochs: 10
  gpus: 1

loader_params:
  batch_size: 32
  num_workers: 1

dataset_params:
  rotate: False
  cache_frames: False
  graph_generation_mode: int_mut
  interaction_dist: 4
  typing_mode: lmg
  rough_search: True
  input_files:
    train:
      - example/ddg_synthetic/FoldX/example_train/data/Synthetic_FoldX_ddG-example_train-w_paths.csv
    val:
      - example/ddg_synthetic/FoldX/example_train/data/Synthetic_FoldX_ddG-example_val-w_paths.csv
    test:
      - example/ddg_synthetic/FoldX/example_train/data/Synthetic_FoldX_ddG-example_test-w_paths.csv
