save_dir: example/ddg_synthetic/FoldX/varying_dataset_size/outputs/
name: Graphinity-subset_900-test
test: True

initialize_weights:
  checkpoint_file: example/ddg_synthetic/FoldX/varying_dataset_size/model_weights/Graphinity-varying_dataset_size-subset_900.ckpt

model: ddgEGNN
model_params:
  num_node_features: 12
  lr: 1.e-3 
  weight_decay: 1.e-16
  balanced_loss: False
  dropout: 0
  num_edge_features: 1
  egnn_layer_hidden_nfs: [128, 128, 128]
  embedding_in_nf: 128
  embedding_out_nf: 128
  num_classes: 1
  attention: False
  residual: True
  normalize: False
  tanh: True
  update_coords: True
  scheduler: CosineAnnealing
  norm_nodes: None
  #max_pool_graphvectors: False #True

trainer_params:
  gpus: 1

loader_params:
  batch_size: 32
  num_workers: 1
  balanced_sampling: False #True

dataset_params:
  rotate: False
  cache_frames: False
  graph_generation_mode: int_mut
  interaction_dist: 4
  typing_mode: lmg
  rough_search: True
  input_files:
    test:
      - example/ddg_synthetic/FoldX/varying_dataset_size/data/Synthetic_FoldX_ddG-varying_dataset_size-test-w_paths.csv
